apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 8080
      protocol: TCP
  selector:
    app: microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  selector:
    matchLabels:
      app: microservice
  replicas: 2 
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: lreimer/continuous-zapk8s:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            port: 8080
            path: /health/liveness
        readinessProbe:
          initialDelaySeconds: 15
          httpGet:
            port: 8080
            path: /health/readiness